use crate::{const_real, duration, rate, unit::*};

impl Unit {
    pub const LURKER: Unit = Unit {
        base: Base::Lurker,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, true, false, true, false, false, false, false, true),
        hull: Health {
            max: const_real!(200),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.9531),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(150),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(0.9375),
        cargo_size: const_real!(4),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const LURKERBURROWED: Unit = Unit {
        base: Base::LurkerBurrowed,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, true, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(200),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(0),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(150),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(0),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::LURKERBURROWED_LURKERMP), None],
    };

    pub const LURKEREGG: Unit = Unit {
        base: Base::LurkerEgg,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(100),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(3.375),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(719.4726),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(0),
            gas: const_real!(0),
            supply: const_real!(0),
            build_time: duration!(0),
        },
        size: const_real!(0.5),
        cargo_size: const_real!(0),
        sight: const_real!(5),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const RAVAGER: Unit = Unit {
        base: Base::Ravager,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(120),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.75),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(100),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(4),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::RAVAGER_RAVAGERWEAPON), None],
    };

    pub const RAVAGERCOCOON: Unit = Unit {
        base: Base::RavagerCocoon,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(100),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(5),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(0),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(0),
            gas: const_real!(0),
            supply: const_real!(0),
            build_time: duration!(0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(0),
        sight: const_real!(5),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const MULE: Unit = Unit {
        base: Base::MULE,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(true, false, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(60),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.8125),
            accel: rate!(2.5),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(50),
            gas: const_real!(0),
            supply: const_real!(0),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(0),
        sight: const_real!(8),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const PROBE: Unit = Unit {
        base: Base::Probe,
        faction: Faction::Protoss,
        collision: Collision::Ground,
        flags: Flags::new(true, false, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(20),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(20),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.8125),
            accel: rate!(2.5),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(50),
            gas: const_real!(0),
            supply: const_real!(1),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(1),
        sight: const_real!(8),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::PROBE_PARTICLEBEAM), None],
    };

    pub const ZEALOT: Unit = Unit {
        base: Base::Zealot,
        faction: Faction::Protoss,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(100),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(50),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(0),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.5),
        cargo_size: const_real!(2),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::ZEALOT_PSIBLADES), None],
    };

    pub const HIGHTEMPLAR: Unit = Unit {
        base: Base::HighTemplar,
        faction: Faction::Protoss,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, true, false, false, true),
        hull: Health {
            max: const_real!(40),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(40),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.0156),
            accel: rate!(1000),
            decel: rate!(1000),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(50),
            gas: const_real!(150),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(2),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(50),
        energy_max: const_real!(200),
        weapons: [Some(Weapon::HIGHTEMPLAR_HIGHTEMPLARWEAPON), None],
    };

    pub const DARKTEMPLAR: Unit = Unit {
        base: Base::DarkTemplar,
        faction: Faction::Protoss,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, true, false, false, false),
        hull: Health {
            max: const_real!(40),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(80),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.8125),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(125),
            gas: const_real!(125),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(2),
        sight: const_real!(8),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::DARKTEMPLAR_WARPBLADES), None],
    };

    pub const OBSERVER: Unit = Unit {
        base: Base::Observer,
        faction: Faction::Protoss,
        collision: Collision::Flying,
        flags: Flags::new(true, false, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(40),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(30),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.0156),
            accel: rate!(2.125),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(25),
            gas: const_real!(75),
            supply: const_real!(1),
            build_time: duration!(0.0),
        },
        size: const_real!(0.5),
        cargo_size: const_real!(0),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const CARRIER: Unit = Unit {
        base: Base::Carrier,
        faction: Faction::Protoss,
        collision: Collision::Flying,
        flags: Flags::new(false, true, true, false, true, false, false, false, false),
        hull: Health {
            max: const_real!(300),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(2),
        },
        shields: Health {
            max: const_real!(150),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(1.875),
            accel: rate!(1.0625),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(350),
            gas: const_real!(250),
            supply: const_real!(6),
            build_time: duration!(0.0),
        },
        size: const_real!(1.25),
        cargo_size: const_real!(0),
        sight: const_real!(12),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const INTERCEPTOR: Unit = Unit {
        base: Base::Interceptor,
        faction: Faction::Protoss,
        collision: Collision::Flying,
        flags: Flags::new(true, false, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(40),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(40),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(7.5),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(15),
            gas: const_real!(0),
            supply: const_real!(0),
            build_time: duration!(0.0),
        },
        size: const_real!(0.25),
        cargo_size: const_real!(0),
        sight: const_real!(7),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::INTERCEPTOR_INTERCEPTORBEAM), None],
    };

    pub const ARCHON: Unit = Unit {
        base: Base::Archon,
        faction: Faction::Protoss,
        collision: Collision::Ground,
        flags: Flags::new(false, false, false, false, true, true, false, false, false),
        hull: Health {
            max: const_real!(10),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(350),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.8125),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(175),
            gas: const_real!(275),
            supply: const_real!(4),
            build_time: duration!(0.0),
        },
        size: const_real!(1),
        cargo_size: const_real!(4),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::ARCHON_PSIONICSHOCKWAVE), None],
    };

    pub const PHOENIX: Unit = Unit {
        base: Base::Phoenix,
        faction: Faction::Protoss,
        collision: Collision::Flying,
        flags: Flags::new(true, false, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(120),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(60),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(4.25),
            accel: rate!(3.25),
            decel: rate!(0),
            turn_rate: rate!(1499.9414),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(100),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(0),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(50),
        energy_max: const_real!(200),
        weapons: [Some(Weapon::PHOENIX_IONCANNONS), None],
    };

    pub const VOIDRAY: Unit = Unit {
        base: Base::VoidRay,
        faction: Faction::Protoss,
        collision: Collision::Flying,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(150),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(100),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.75),
            accel: rate!(2),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(250),
            gas: const_real!(150),
            supply: const_real!(4),
            build_time: duration!(0.0),
        },
        size: const_real!(1),
        cargo_size: const_real!(0),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::VOIDRAY_VOIDRAYSWARM), None],
    };

    pub const WARPPRISM: Unit = Unit {
        base: Base::WarpPrism,
        faction: Faction::Protoss,
        collision: Collision::Flying,
        flags: Flags::new(false, true, true, false, false, true, false, false, false),
        hull: Health {
            max: const_real!(80),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(100),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.9531),
            accel: rate!(2.625),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(57),
        },
        cost: Cost {
            minerals: const_real!(250),
            gas: const_real!(0),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.875),
        cargo_size: const_real!(0),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const STALKER: Unit = Unit {
        base: Base::Stalker,
        faction: Faction::Protoss,
        collision: Collision::Ground,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(80),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(80),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.9531),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(125),
            gas: const_real!(50),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.625),
        cargo_size: const_real!(2),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::STALKER_PARTICLEDISRUPTORS), None],
    };

    pub const COLOSSUS: Unit = Unit {
        base: Base::Colossus,
        faction: Faction::Protoss,
        collision: Collision::Both,
        flags: Flags::new(false, true, true, false, true, false, false, false, false),
        hull: Health {
            max: const_real!(200),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(150),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(300),
            gas: const_real!(200),
            supply: const_real!(6),
            build_time: duration!(0.0),
        },
        size: const_real!(1),
        cargo_size: const_real!(8),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::COLOSSUS_THERMALLANCES), None],
    };

    pub const MOTHERSHIP: Unit = Unit {
        base: Base::Mothership,
        faction: Faction::Protoss,
        collision: Collision::Flying,
        flags: Flags::new(false, true, true, false, true, true, false, true, false),
        hull: Health {
            max: const_real!(250),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(2),
        },
        shields: Health {
            max: const_real!(250),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.0156),
            accel: rate!(1.375),
            decel: rate!(1),
            turn_rate: rate!(720),
            lateral_accel: rate!(2.0625),
        },
        cost: Cost {
            minerals: const_real!(300),
            gas: const_real!(300),
            supply: const_real!(6),
            build_time: duration!(0.0),
        },
        size: const_real!(1.25),
        cargo_size: const_real!(0),
        sight: const_real!(14),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::MOTHERSHIP_MOTHERSHIPBEAM), None],
    };

    pub const SCV: Unit = Unit {
        base: Base::SCV,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(true, false, true, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(45),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.8125),
            accel: rate!(2.5),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(50),
            gas: const_real!(0),
            supply: const_real!(1),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(1),
        sight: const_real!(8),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::SCV_FUSIONCUTTER), None],
    };

    pub const MARINE: Unit = Unit {
        base: Base::Marine,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(45),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(50),
            gas: const_real!(0),
            supply: const_real!(1),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(1),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::MARINE_GUASSRIFLE), None],
    };

    pub const REAPER: Unit = Unit {
        base: Base::Reaper,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(60),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(3.75),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(50),
            gas: const_real!(50),
            supply: const_real!(1),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(1),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::REAPER_P38SCYTHEGUASSPISTOL), None],
    };

    pub const GHOST: Unit = Unit {
        base: Base::Ghost,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(false, false, false, true, false, true, false, false, false),
        hull: Health {
            max: const_real!(100),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.8125),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(125),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(2),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(75),
        energy_max: const_real!(200),
        weapons: [Some(Weapon::GHOST_C10CANISTERRIFLE), None],
    };

    pub const SIEGETANK: Unit = Unit {
        base: Base::SiegeTank,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(175),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(360),
            lateral_accel: rate!(64),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(125),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(0.875),
        cargo_size: const_real!(4),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::SIEGETANK_90MMCANNONS), None],
    };

    pub const SIEGETANKSIEGED: Unit = Unit {
        base: Base::SiegeTankSieged,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(175),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(0),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(360),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(125),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(0.875),
        cargo_size: const_real!(0),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::SIEGETANKSIEGED_CRUCIOSHOCKCANNON), None],
    };

    pub const THOR: Unit = Unit {
        base: Base::Thor,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(false, true, true, false, true, false, false, false, false),
        hull: Health {
            max: const_real!(400),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(1.875),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(360),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(300),
            gas: const_real!(200),
            supply: const_real!(6),
            build_time: duration!(0.0),
        },
        size: const_real!(1),
        cargo_size: const_real!(8),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [
            Some(Weapon::THOR_JAVELINMISSILELAUNCHERS),
            Some(Weapon::THOR_THORSHAMMER),
        ],
    };

    pub const THORALT: Unit = Unit {
        base: Base::ThorAlt,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(false, true, true, false, true, false, false, false, false),
        hull: Health {
            max: const_real!(400),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(1.875),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(360),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(300),
            gas: const_real!(200),
            supply: const_real!(6),
            build_time: duration!(0.0),
        },
        size: const_real!(1),
        cargo_size: const_real!(8),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [
            Some(Weapon::THORALT_LANCEMISSILELAUNCHERS),
            Some(Weapon::THORALT_THORSHAMMER),
        ],
    };

    pub const BANSHEE: Unit = Unit {
        base: Base::Banshee,
        faction: Faction::Terran,
        collision: Collision::Flying,
        flags: Flags::new(true, false, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(140),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.75),
            accel: rate!(3.25),
            decel: rate!(0),
            turn_rate: rate!(1499.9414),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(100),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(0),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(50),
        energy_max: const_real!(200),
        weapons: [Some(Weapon::BANSHEE_BACKLASHROCKETS), None],
    };

    pub const MEDIVAC: Unit = Unit {
        base: Base::Medivac,
        faction: Faction::Terran,
        collision: Collision::Flying,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(150),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.5),
            accel: rate!(2.25),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(1000),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(100),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(0),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(50),
        energy_max: const_real!(200),
        weapons: [None, None],
    };

    pub const BATTLECRUISER: Unit = Unit {
        base: Base::Battlecruiser,
        faction: Faction::Terran,
        collision: Collision::Flying,
        flags: Flags::new(false, true, true, false, true, false, false, false, false),
        hull: Health {
            max: const_real!(550),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(3),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(1.875),
            accel: rate!(1),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(400),
            gas: const_real!(300),
            supply: const_real!(6),
            build_time: duration!(0.0),
        },
        size: const_real!(1.25),
        cargo_size: const_real!(0),
        sight: const_real!(12),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [
            Some(Weapon::BATTLECRUISER_BATTLECRUISERWEAPONSWITCH),
            Some(Weapon::BATTLECRUISER_ATALASERBATTERY),
        ],
    };

    pub const RAVEN: Unit = Unit {
        base: Base::Raven,
        faction: Faction::Terran,
        collision: Collision::Flying,
        flags: Flags::new(true, false, true, false, false, false, false, false, true),
        hull: Health {
            max: const_real!(140),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.9492),
            accel: rate!(2),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(150),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.625),
        cargo_size: const_real!(0),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(50),
        energy_max: const_real!(200),
        weapons: [None, None],
    };

    pub const VIKINGGROUND: Unit = Unit {
        base: Base::VikingGround,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(135),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(75),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(2),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::VIKINGGROUND_TWINGATLINGCANNON), None],
    };

    pub const VIKINGAIR: Unit = Unit {
        base: Base::VikingAir,
        faction: Faction::Terran,
        collision: Collision::Flying,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(135),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.75),
            accel: rate!(2.625),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(75),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(0),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::VIKINGAIR_LANZERTORPEDOES), None],
    };

    pub const LARVA: Unit = Unit {
        base: Base::Larva,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(25),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(10),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(0.5625),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(0),
            gas: const_real!(0),
            supply: const_real!(0),
            build_time: duration!(0),
        },
        size: const_real!(0.125),
        cargo_size: const_real!(0),
        sight: const_real!(5),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const DRONE: Unit = Unit {
        base: Base::Drone,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(40),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.8125),
            accel: rate!(2.5),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(50),
            gas: const_real!(0),
            supply: const_real!(1),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(1),
        sight: const_real!(8),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::DRONE_SPINES), None],
    };

    pub const ROACH: Unit = Unit {
        base: Base::Roach,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, true, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(145),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(75),
            gas: const_real!(25),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.5),
        cargo_size: const_real!(2),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [
            Some(Weapon::ROACH_ROACHMELEE),
            Some(Weapon::ROACH_ACIDSALIVA),
        ],
    };

    pub const ROACHBURROWED: Unit = Unit {
        base: Base::RoachBurrowed,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, true, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(145),
            regen: rate!(5),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(0),
            accel: rate!(0),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(75),
            gas: const_real!(25),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.5),
        cargo_size: const_real!(0),
        sight: const_real!(5),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const OVERLORD: Unit = Unit {
        base: Base::Overlord,
        faction: Faction::Zerg,
        collision: Collision::Flying,
        flags: Flags::new(false, true, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(200),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(0.6445),
            accel: rate!(1.0625),
            decel: rate!(1.625),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(0),
            supply: const_real!(0),
            build_time: duration!(0.0),
        },
        size: const_real!(1),
        cargo_size: const_real!(0),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const OVERSEER: Unit = Unit {
        base: Base::Overseer,
        faction: Faction::Zerg,
        collision: Collision::Flying,
        flags: Flags::new(false, true, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(200),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(1.875),
            accel: rate!(2.125),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(50),
            supply: const_real!(0),
            build_time: duration!(0.0),
        },
        size: const_real!(1),
        cargo_size: const_real!(0),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(50),
        energy_max: const_real!(200),
        weapons: [None, None],
    };

    pub const ZERGLING: Unit = Unit {
        base: Base::Zergling,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(35),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.9531),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(25),
            gas: const_real!(0),
            supply: const_real!(0.5),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(1),
        sight: const_real!(8),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::ZERGLING_CLAWS), None],
    };

    pub const HYDRALISK: Unit = Unit {
        base: Base::Hydralisk,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(90),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(50),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.625),
        cargo_size: const_real!(2),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [
            Some(Weapon::HYDRALISK_HYDRALISKMELEE),
            Some(Weapon::HYDRALISK_NEEDLESPINES),
        ],
    };

    pub const MUTALISK: Unit = Unit {
        base: Base::Mutalisk,
        faction: Faction::Zerg,
        collision: Collision::Flying,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(120),
            regen: rate!(1),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(4),
            accel: rate!(3.5),
            decel: rate!(0),
            turn_rate: rate!(1499.9414),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(100),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.5),
        cargo_size: const_real!(0),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::MUTALISK_GLAIVEWURM), None],
    };

    pub const ULTRALISK: Unit = Unit {
        base: Base::Ultralisk,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, true, false, true, true, false, false, false, false),
        hull: Health {
            max: const_real!(500),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(2),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.9531),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(360),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(275),
            gas: const_real!(200),
            supply: const_real!(6),
            build_time: duration!(0.0),
        },
        size: const_real!(0.875),
        cargo_size: const_real!(8),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::ULTRALISK_KAISERBLADES), None],
    };

    pub const BANELING: Unit = Unit {
        base: Base::Baneling,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(30),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.5),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(50),
            gas: const_real!(25),
            supply: const_real!(0.5),
            build_time: duration!(0.0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(2),
        sight: const_real!(8),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [
            Some(Weapon::BANELING_VOLATILEBURST),
            Some(Weapon::BANELING_VOLATILEBURSTBUILDING),
        ],
    };

    pub const INFESTOR: Unit = Unit {
        base: Base::Infestor,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, true, false, true, false, true, false, false, true),
        hull: Health {
            max: const_real!(90),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(150),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.625),
        cargo_size: const_real!(2),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(75),
        energy_max: const_real!(200),
        weapons: [None, None],
    };

    pub const INFESTORBURROWED: Unit = Unit {
        base: Base::InfestorBurrowed,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, true, false, true, false, true, false, false, false),
        hull: Health {
            max: const_real!(90),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(150),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.625),
        cargo_size: const_real!(2),
        sight: const_real!(8),
        push_priority: const_real!(10),
        energy_start: const_real!(75),
        energy_max: const_real!(200),
        weapons: [None, None],
    };

    pub const IMMORTAL: Unit = Unit {
        base: Base::Immortal,
        faction: Faction::Protoss,
        collision: Collision::Ground,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(200),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(100),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(275),
            gas: const_real!(100),
            supply: const_real!(4),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(4),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::IMMORTAL_PHASEDISRUPTORS), None],
    };

    pub const MARAUDER: Unit = Unit {
        base: Base::Marauder,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(false, true, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(125),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(69.125),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(25),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.5625),
        cargo_size: const_real!(2),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::MARAUDER_PUNISHERGRENADES), None],
    };

    pub const BROODLORD: Unit = Unit {
        base: Base::BroodLord,
        faction: Faction::Zerg,
        collision: Collision::Flying,
        flags: Flags::new(false, true, false, true, true, false, false, false, false),
        hull: Health {
            max: const_real!(225),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(1.875),
            accel: rate!(1.0625),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(300),
            gas: const_real!(250),
            supply: const_real!(4),
            build_time: duration!(0.0),
        },
        size: const_real!(1),
        cargo_size: const_real!(0),
        sight: const_real!(12),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::BROODLORD_BROODLINGSTRIKE), None],
    };

    pub const BROODLING: Unit = Unit {
        base: Base::Broodling,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(30),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(0),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(0),
            gas: const_real!(0),
            supply: const_real!(0),
            build_time: duration!(0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(0),
        sight: const_real!(7),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const CORRUPTOR: Unit = Unit {
        base: Base::Corruptor,
        faction: Faction::Zerg,
        collision: Collision::Flying,
        flags: Flags::new(false, true, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(200),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(2),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(3.375),
            accel: rate!(3),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(100),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.625),
        cargo_size: const_real!(0),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::CORRUPTOR_PARASITESPORE), None],
    };

    pub const SENTRY: Unit = Unit {
        base: Base::Sentry,
        faction: Faction::Protoss,
        collision: Collision::Ground,
        flags: Flags::new(true, false, true, false, false, true, false, false, false),
        hull: Health {
            max: const_real!(40),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(40),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.5),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(50),
            gas: const_real!(100),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.5),
        cargo_size: const_real!(2),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(50),
        energy_max: const_real!(200),
        weapons: [Some(Weapon::SENTRY_DISRUPTIONBEAM), None],
    };

    pub const QUEEN: Unit = Unit {
        base: Base::Queen,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, false, false, true, false, true, false, false, false),
        hull: Health {
            max: const_real!(175),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(0.9375),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(0),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.875),
        cargo_size: const_real!(2),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(25),
        energy_max: const_real!(200),
        weapons: [
            Some(Weapon::QUEEN_ACIDSPINES),
            Some(Weapon::QUEEN_TALONSMISSILE),
        ],
    };

    pub const HELLION: Unit = Unit {
        base: Base::Hellion,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(true, false, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(90),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(4.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(0),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.625),
        cargo_size: const_real!(2),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::HELLION_INFERNALFLAMETHROWER), None],
    };

    pub const CHANGELING: Unit = Unit {
        base: Base::Changeling,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(5),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(0),
            gas: const_real!(0),
            supply: const_real!(0),
            build_time: duration!(0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(0),
        sight: const_real!(8),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const ORACLE: Unit = Unit {
        base: Base::Oracle,
        faction: Faction::Protoss,
        collision: Collision::Flying,
        flags: Flags::new(true, true, true, false, false, true, false, false, true),
        hull: Health {
            max: const_real!(100),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(60),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(4),
            accel: rate!(3),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(150),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(0),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(50),
        energy_max: const_real!(200),
        weapons: [Some(Weapon::ORACLE_ORACLE), None],
    };

    pub const HELLBAT: Unit = Unit {
        base: Base::Hellbat,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(true, false, true, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(135),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(46),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(0),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.625),
        cargo_size: const_real!(4),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::HELLBAT_HELLIONTANK), None],
    };

    pub const SWARMHOST: Unit = Unit {
        base: Base::SwarmHost,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(false, true, false, true, false, false, false, false, true),
        hull: Health {
            max: const_real!(160),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(360),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(75),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(0.8125),
        cargo_size: const_real!(4),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const LOCUST: Unit = Unit {
        base: Base::Locust,
        faction: Faction::Zerg,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(50),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(1.875),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(0),
            gas: const_real!(0),
            supply: const_real!(0),
            build_time: duration!(0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(0),
        sight: const_real!(6),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [
            Some(Weapon::LOCUST_LOCUSTMPMELEE),
            Some(Weapon::LOCUST_LOCUSTMP),
        ],
    };

    pub const TEMPEST: Unit = Unit {
        base: Base::Tempest,
        faction: Faction::Protoss,
        collision: Collision::Flying,
        flags: Flags::new(false, true, true, false, true, false, false, false, false),
        hull: Health {
            max: const_real!(200),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(2),
        },
        shields: Health {
            max: const_real!(100),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(3),
            decel: rate!(3),
            turn_rate: rate!(720),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(250),
            gas: const_real!(175),
            supply: const_real!(5),
            build_time: duration!(0.0),
        },
        size: const_real!(1.125),
        cargo_size: const_real!(0),
        sight: const_real!(12),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [
            Some(Weapon::TEMPEST_TEMPEST),
            Some(Weapon::TEMPEST_TEMPESTGROUND),
        ],
    };

    pub const VIPER: Unit = Unit {
        base: Base::Viper,
        faction: Faction::Zerg,
        collision: Collision::Flying,
        flags: Flags::new(false, true, false, true, false, true, false, false, true),
        hull: Health {
            max: const_real!(150),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.9531),
            accel: rate!(3),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(200),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(1),
        cargo_size: const_real!(0),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(50),
        energy_max: const_real!(200),
        weapons: [None, None],
    };

    pub const WIDOWMINE: Unit = Unit {
        base: Base::WidowMine,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(true, false, true, false, false, false, false, false, true),
        hull: Health {
            max: const_real!(90),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.8125),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(75),
            gas: const_real!(25),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.5),
        cargo_size: const_real!(2),
        sight: const_real!(7),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const WIDOWMINEBURROWED: Unit = Unit {
        base: Base::WidowMineBurrowed,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(true, false, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(90),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(0),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(75),
            gas: const_real!(25),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.5),
        cargo_size: const_real!(0),
        sight: const_real!(7),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const CYCLONE: Unit = Unit {
        base: Base::Cyclone,
        faction: Faction::Terran,
        collision: Collision::Ground,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(130),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.8125),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(360),
            lateral_accel: rate!(64),
        },
        cost: Cost {
            minerals: const_real!(125),
            gas: const_real!(50),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(4),
        sight: const_real!(11),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [
            Some(Weapon::CYCLONE_TYPHOONMISSILEPOD),
            Some(Weapon::CYCLONE_CYCLONEFAKEWEAPON),
        ],
    };

    pub const LOCUSTFLYING: Unit = Unit {
        base: Base::LocustFlying,
        faction: Faction::Zerg,
        collision: Collision::Flying,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(50),
            regen: rate!(0.2734),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(1.875),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(720),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(0),
            gas: const_real!(0),
            supply: const_real!(0),
            build_time: duration!(0),
        },
        size: const_real!(0.375),
        cargo_size: const_real!(0),
        sight: const_real!(6),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::LOCUSTFLYING_LOCUSTMPFLYINGSWOOPWEAPON), None],
    };

    pub const DISRUPTOR: Unit = Unit {
        base: Base::Disruptor,
        faction: Faction::Protoss,
        collision: Collision::Ground,
        flags: Flags::new(true, true, true, false, false, false, false, false, true),
        hull: Health {
            max: const_real!(100),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(100),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.25),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(150),
            supply: const_real!(4),
            build_time: duration!(0.0),
        },
        size: const_real!(0.625),
        cargo_size: const_real!(4),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [None, None],
    };

    pub const ADEPT: Unit = Unit {
        base: Base::Adept,
        faction: Faction::Protoss,
        collision: Collision::Ground,
        flags: Flags::new(true, false, false, true, false, false, false, false, false),
        hull: Health {
            max: const_real!(70),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(1),
        },
        shields: Health {
            max: const_real!(70),
            regen: rate!(2),
            delay: duration!(10),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(2.5),
            accel: rate!(1000),
            decel: rate!(0),
            turn_rate: rate!(999.8437),
            lateral_accel: rate!(46.0625),
        },
        cost: Cost {
            minerals: const_real!(100),
            gas: const_real!(25),
            supply: const_real!(2),
            build_time: duration!(0.0),
        },
        size: const_real!(0.5),
        cargo_size: const_real!(2),
        sight: const_real!(9),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::ADEPT_ADEPT), None],
    };

    pub const LIBERATOR: Unit = Unit {
        base: Base::Liberator,
        faction: Faction::Terran,
        collision: Collision::Flying,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(180),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(3.375),
            accel: rate!(3.5),
            decel: rate!(0),
            turn_rate: rate!(1499.9414),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(125),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(0),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::LIBERATOR_LIBERATORMISSILELAUNCHERS), None],
    };

    pub const LIBERATORSIEGED: Unit = Unit {
        base: Base::LiberatorSieged,
        faction: Faction::Terran,
        collision: Collision::Flying,
        flags: Flags::new(false, true, true, false, false, false, false, false, false),
        hull: Health {
            max: const_real!(180),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        shields: Health {
            max: const_real!(0),
            regen: rate!(0),
            delay: duration!(0),
            armor: const_real!(0),
        },
        movement: Movement {
            speed: rate!(0),
            accel: rate!(3.5),
            decel: rate!(0),
            turn_rate: rate!(1499.9414),
            lateral_accel: rate!(0),
        },
        cost: Cost {
            minerals: const_real!(150),
            gas: const_real!(125),
            supply: const_real!(3),
            build_time: duration!(0.0),
        },
        size: const_real!(0.75),
        cargo_size: const_real!(0),
        sight: const_real!(10),
        push_priority: const_real!(10),
        energy_start: const_real!(0),
        energy_max: const_real!(0),
        weapons: [Some(Weapon::LIBERATORSIEGED_LIBERATORAGWEAPON), None],
    };
}
