use crate::{const_real, duration, unit::*,};

impl Weapon {
pub const BROODLING_NEEDLECLAWS: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(4),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.1)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.8),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const LURKERBURROWED_LURKERMP: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(20),
bonus_damage: const_real!(10),
bonus_vs: Some(Flag::Armored),
can_target: Collision::Ground,
upgrade_inc: [const_real!(2), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(8)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(2),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const RAVAGER_RAVAGERWEAPON: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(16),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(2), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.6),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.2),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const PROBE_PARTICLEBEAM: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(5),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(0), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.2)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.5),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const ZEALOT_PSIBLADES: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(8),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.1)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.2),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const HIGHTEMPLAR_HIGHTEMPLARWEAPON: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(4),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.754),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const DARKTEMPLAR_WARPBLADES: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(45),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(5), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.1)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.694),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.361),
backswing: duration!(1.333),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const INTERCEPTOR_INTERCEPTORBEAM: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(5),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(2)),
range_slop: const_real!(1),
arc: const_real!(19.6875),
arc_slop: const_real!(11.25),
attack_speed: duration!(3),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const ARCHON_PSIONICSHOCKWAVE: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(25),
bonus_damage: const_real!(10),
bonus_vs: Some(Flag::Biological),
can_target: Collision::Both,
upgrade_inc: [const_real!(3), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(3)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.754),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const PHOENIX_IONCANNONS: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(5),
bonus_damage: const_real!(5),
bonus_vs: Some(Flag::Light),
can_target: Collision::Flying,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(5)),
range_slop: const_real!(1),
arc: const_real!(4.9987),
arc_slop: const_real!(0),
attack_speed: duration!(1.1),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const VOIDRAY_VOIDRAYSWARM: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(6),
bonus_damage: const_real!(4),
bonus_vs: Some(Flag::Armored),
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(2),
arc: const_real!(0),
arc_slop: const_real!(39.9902),
attack_speed: duration!(0.5),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.75),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const STALKER_PARTICLEDISRUPTORS: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(13),
bonus_damage: const_real!(5),
bonus_vs: Some(Flag::Armored),
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.87),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const COLOSSUS_THERMALLANCES: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(10),
bonus_damage: const_real!(5),
bonus_vs: Some(Flag::Light),
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(7)),
range_slop: const_real!(0),
arc: const_real!(90),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.5),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.0832),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const MOTHERSHIP_MOTHERSHIPBEAM: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(6),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(7)),
range_slop: const_real!(1),
arc: const_real!(360),
arc_slop: const_real!(11.25),
attack_speed: duration!(2.21),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(6)),
search: SearchType::Single,
effect: None,
};

pub const SCV_FUSIONCUTTER: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(5),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(0), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.2)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.5),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const MARINE_GUASSRIFLE: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(6),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(5)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.8608),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.05),
backswing: duration!(0.75),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const REAPER_P38SCYTHEGUASSPISTOL: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(4),
bonus_damage: const_real!(0),
bonus_vs: Some(Flag::Light),
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(5)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.1),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0),
backswing: duration!(0.75),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const GHOST_C10CANISTERRIFLE: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(10),
bonus_damage: const_real!(10),
bonus_vs: Some(Flag::Light),
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.5),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.083),
backswing: duration!(1.167),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const SIEGETANK_90MMCANNONS: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(15),
bonus_damage: const_real!(10),
bonus_vs: Some(Flag::Armored),
can_target: Collision::Ground,
upgrade_inc: [const_real!(2), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(7)),
range_slop: const_real!(1),
arc: const_real!(360),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.04),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const SIEGETANKSIEGED_CRUCIOSHOCKCANNON: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(40),
bonus_damage: const_real!(30),
bonus_vs: Some(Flag::Armored),
can_target: Collision::Ground,
upgrade_inc: [const_real!(4), const_real!(1)],
range: RangeInclusive::new(const_real!(2), const_real!(13)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(3),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const THOR_JAVELINMISSILELAUNCHERS: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(6),
bonus_damage: const_real!(6),
bonus_vs: Some(Flag::Light),
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(10)),
range_slop: const_real!(1),
arc: const_real!(5.625),
arc_slop: const_real!(11.25),
attack_speed: duration!(3),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(4)),
search: SearchType::Single,
effect: None,
};

pub const THOR_THORSHAMMER: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(30),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(3), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(7)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.28),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.831),
backswing: duration!(0.25),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const THORALT_LANCEMISSILELAUNCHERS: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(25),
bonus_damage: const_real!(10),
bonus_vs: Some(Flag::Massive),
can_target: Collision::Flying,
upgrade_inc: [const_real!(3), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(11)),
range_slop: const_real!(1),
arc: const_real!(5.625),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.28),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const THORALT_THORSHAMMER: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(30),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(3), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(7)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.28),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.831),
backswing: duration!(0.25),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const BANSHEE_BACKLASHROCKETS: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(12),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.25),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const BATTLECRUISER_BATTLECRUISERWEAPONSWITCH: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(8),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(360),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.225),
random_delay: RangeInclusive::new(duration!(0), duration!(0)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const BATTLECRUISER_ATALASERBATTERY: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(5),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Flying,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(360),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.225),
random_delay: RangeInclusive::new(duration!(0), duration!(0)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const VIKINGGROUND_TWINGATLINGCANNON: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(12),
bonus_damage: const_real!(8),
bonus_vs: Some(Flag::Mechanical),
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(5.625),
arc_slop: const_real!(11.25),
attack_speed: duration!(1),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const VIKINGAIR_LANZERTORPEDOES: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(10),
bonus_damage: const_real!(4),
bonus_vs: Some(Flag::Armored),
can_target: Collision::Flying,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(9)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(2),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.05),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const DRONE_SPINES: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(5),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(0), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.2)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.5),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const ROACH_ROACHMELEE: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(16),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(2), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.5)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(2),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const ROACH_ACIDSALIVA: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(16),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(2), const_real!(0)],
range: RangeInclusive::new(const_real!(0.6), const_real!(4)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(2),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const ZERGLING_CLAWS: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(5),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.1)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.696),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const HYDRALISK_HYDRALISKMELEE: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(12),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.5)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.825),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.14),
backswing: duration!(0.5607),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const HYDRALISK_NEEDLESPINES: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(12),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(5)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.825),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.14),
backswing: duration!(0.5607),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const MUTALISK_GLAIVEWURM: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(9),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(3)),
range_slop: const_real!(2),
arc: const_real!(0),
arc_slop: const_real!(45),
attack_speed: duration!(1.5246),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const ULTRALISK_KAISERBLADES: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(35),
bonus_damage: const_real!(0),
bonus_vs: Some(Flag::Armored),
can_target: Collision::Ground,
upgrade_inc: [const_real!(3), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(1)),
range_slop: const_real!(1.25),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.86),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.3332),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const BANELING_VOLATILEBURST: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(16),
bonus_damage: const_real!(19),
bonus_vs: Some(Flag::Light),
can_target: Collision::Ground,
upgrade_inc: [const_real!(0), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.25)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.833),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const BANELING_VOLATILEBURSTBUILDING: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(16),
bonus_damage: const_real!(19),
bonus_vs: Some(Flag::Light),
can_target: Collision::Ground,
upgrade_inc: [const_real!(0), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.25)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.833),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const IMMORTAL_PHASEDISRUPTORS: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(20),
bonus_damage: const_real!(30),
bonus_vs: Some(Flag::Armored),
can_target: Collision::Ground,
upgrade_inc: [const_real!(2), const_real!(3)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.45),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const MARAUDER_PUNISHERGRENADES: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(10),
bonus_damage: const_real!(10),
bonus_vs: Some(Flag::Armored),
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.5),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0),
backswing: duration!(0),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const BROODLORD_BROODLINGSTRIKE: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(20),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(2), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(10)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(2.5),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const CORRUPTOR_PARASITESPORE: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(14),
bonus_damage: const_real!(6),
bonus_vs: Some(Flag::Massive),
can_target: Collision::Flying,
upgrade_inc: [const_real!(1), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.9),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.0625),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const SENTRY_DISRUPTIONBEAM: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(6),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(5)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const QUEEN_ACIDSPINES: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(9),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Flying,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(7)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const QUEEN_TALONS: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(4),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(3)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const QUEEN_TALONSMISSILE: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(4),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(3), const_real!(5)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const HELLION_INFERNALFLAMETHROWER: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(8),
bonus_damage: const_real!(6),
bonus_vs: Some(Flag::Light),
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(5)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(2.5),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.25),
backswing: duration!(0.75),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const ORACLE_ORACLE: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(15),
bonus_damage: const_real!(7),
bonus_vs: Some(Flag::Light),
can_target: Collision::Ground,
upgrade_inc: [const_real!(0), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(4)),
range_slop: const_real!(0),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.86),
random_delay: RangeInclusive::new(duration!(0), duration!(0)),
damage_point: duration!(0.167),
backswing: duration!(0.75),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const HELLBAT_HELLIONTANK: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(18),
bonus_damage: const_real!(0),
bonus_vs: Some(Flag::Light),
can_target: Collision::Ground,
upgrade_inc: [const_real!(2), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(2)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(2),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const LOCUST_LOCUSTMPMELEE: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(10),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(0.5)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.6),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.2666),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const LOCUST_LOCUSTMP: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(10),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(3)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.6),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.2666),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const TEMPEST_TEMPEST: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(30),
bonus_damage: const_real!(22),
bonus_vs: Some(Flag::Massive),
can_target: Collision::Flying,
upgrade_inc: [const_real!(3), const_real!(2)],
range: RangeInclusive::new(const_real!(0), const_real!(14)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(3.3),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const TEMPEST_TEMPESTGROUND: Weapon = Weapon {
kind: WeaponKind::Projectile,
damage: const_real!(40),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(4), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(10)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(3.3),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const CYCLONE_TYPHOONMISSILEPOD: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(11),
bonus_damage: const_real!(3),
bonus_vs: Some(Flag::Mechanical),
can_target: Collision::Both,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.812),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.05),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const CYCLONE_CYCLONEFAKEWEAPON: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(20),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Both,
upgrade_inc: [const_real!(0), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const LOCUSTFLYING_LOCUSTMPFLYINGSWOOPWEAPON: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(10),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(6)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(0.8),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const ADEPT_ADEPT: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(10),
bonus_damage: const_real!(12),
bonus_vs: Some(Flag::Light),
can_target: Collision::Ground,
upgrade_inc: [const_real!(1), const_real!(1)],
range: RangeInclusive::new(const_real!(0), const_real!(4)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(2.25),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

pub const LIBERATOR_LIBERATORMISSILELAUNCHERS: Weapon = Weapon {
kind: WeaponKind::Hitscan,
damage: const_real!(5),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Flying,
upgrade_inc: [const_real!(1), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(5)),
range_slop: const_real!(1),
arc: const_real!(0),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.8),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.167),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Instant(const_real!(2)),
search: SearchType::Single,
effect: None,
};

pub const LIBERATORSIEGED_LIBERATORAGWEAPON: Weapon = Weapon {
kind: WeaponKind::Melee,
damage: const_real!(75),
bonus_damage: const_real!(0),
bonus_vs: None,
can_target: Collision::Ground,
upgrade_inc: [const_real!(5), const_real!(0)],
range: RangeInclusive::new(const_real!(0), const_real!(10)),
range_slop: const_real!(0),
arc: const_real!(360),
arc_slop: const_real!(11.25),
attack_speed: duration!(1.6),
random_delay: RangeInclusive::new(duration!(-0.0625), duration!(1.25)),
damage_point: duration!(0.125),
backswing: duration!(0.5),
priority: Priority::Normal,
multihit: Multihit::Single,
search: SearchType::Single,
effect: None,
};

}
