[package]
name = "sc2_xml"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
itertools = "0.13"
paste = "1.0"
quanta = "0.12"
roxmltree = "0.20"
static_init = "1.0"
indexmap = "2.2"



[profile.dev.package."*"]
opt-level = 3
