[package]
name = "sc2_xml"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = "0.2.1"
itertools = "0.13.0"
paste = "1.0.14"
quanta = "0.12.3"
roxmltree = "0.20.0"
static_init = "1.0.3"
indexmap = "2.2.6"


[profile.dev.package."*"]
opt-level = 3
